/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLogo: typeof import('./../components/AppLogo.vue')['default']
    AppView: typeof import('./../components/AppView.vue')['default']
    ButtonAnimation: typeof import('./../components/button-animation/ButtonAnimation.vue')['default']
    ButtonAnimationProvider: typeof import('./../components/button-animation/ButtonAnimationProvider.vue')['default']
    CollapseTransition: typeof import('./../components/collapse-transition/CollapseTransition.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NEl: typeof import('naive-ui')['NEl']
    NFlex: typeof import('naive-ui')['NFlex']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NH2: typeof import('naive-ui')['NH2']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModalProvider: typeof import('naive-ui')['NModalProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NResult: typeof import('naive-ui')['NResult']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserAvatar: typeof import('./../components/UserAvatar.vue')['default']
    UserDropdown: typeof import('./../components/UserDropdown.vue')['default']
  }
}
