spring:
  application:
    name: four-zero-four
  messages:
    basename: i18n/commons,i18n/api,i18n/bug,i18n/case,i18n/plan,i18n/project,i18n/system,i18n/dashboard
    default-locale: zh_CN
  profiles:
    active: dev